CROSS_COMPILE := /home/mlainani/factory/build_armv7l-timesys-linux-uclibcgnueabi/toolchain/bin/armv7l-timesys-linux-uclibcgnueabi-
CC := $(CROSS_COMPILE)gcc

rthdr: rthdr.c
	$(CC) -o rthdr rthdr.c

rplopt: rplopt.c
	$(CC) -o rplopt rplopt.c

